name: CI

# Continuous integration will run whenever a pull request for the master branch
# is created or updated.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Check out FlowGo
        uses: actions/checkout@v2
        with:
          repository: onflow/flow-go
          ref: c0afa789365eb7a22713ed76b8de1e3efaf3a70a
          path: flow-go

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Here, we simply print the exact go version, to have it as part of the
      # action's output, which might be convenient.
      - name: Print Go version
        run: go version

      # Since building relic takes some time, we want to cache it.
      - name: Cache Crypto package
        uses: actions/cache@v2
        with:
          path: ./flow-go/crypto
          key: ${{ runner.os }}-crypto
          restore-keys: |
            ${{ runner.os }}-crypto

      # In order to be able to build with flow-go and the relic tag, we need to
      # run its go generate target.
      - name: Install Flow Go's crypto
        run: |
          cd ./flow-go/crypto
          go generate .

      # This check makes sure that the `go.mod` and `go.sum` files for Go
      # modules are always up-to-date.
      - name: Verify Go modules
        run: go mod tidy && git status && git --no-pager diff && git diff-index --quiet HEAD --

      # This check makes sure that the source code is formatted according to the
      # Go standard `go fmt` formatting.
      - name: Verify source code formatting
        run: go fmt ./... && git status && git --no-pager diff && git diff-index --quiet HEAD --

      # This check makes sure that we can compile the binary as a pure Go binary
      # without CGO support.
      - name: Verify compilation
        run: go build -tags relic ./...

      # This check runs all unit tests with verbose output and ensures that all
      # of the tests pass successfully.
      - name: Verify unit tests
        run: go test -tags relic -v ./...

      # This check runs all integration tests with verbose output and ensures
      # that they pass successfully.
      - name: Verify integration tests
        run: go test -v -tags="relic integration" ./...
